"""Abstract object describing a security acceptance transaction"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.2.0/schema/primitives/objects/transactions/acceptance/Acceptance.schema.j
# son

from pydantic import BaseModel


class Acceptance(BaseModel):
    """Abstract object describing a security acceptance transaction"""
