"""Abstract object describing a security acceptance transaction"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/main/schema/primitives/objects/transactions/acceptance/Acceptance.schema.jso
# n

from pydantic import BaseModel


class Acceptance(BaseModel):
    """Abstract object describing a security acceptance transaction"""
