"""Abstract object describing fields common to all conversion transaction objects"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.2.0/schema/primitives/objects/transactions/conversion/Conversion.schema.j
# son

from pydantic import BaseModel
from pydantic import Field
from typing import Annotated


class Conversion(BaseModel):
    """Abstract object describing fields common to all conversion transaction objects"""

    resulting_security_ids: Annotated[
        list[str],
        Field(
            description="Identifier for the security (or securities) that resulted from the conversion"
        ),
    ]
