"""Describes a vesting condition satisfied when a particular unscheduled event
occurs"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/types/vesting/VestingEventTrigger.schema.json

from pydantic import Field
from pyocf.primitives.types.vesting.vestingconditiontrigger import (
    VestingConditionTrigger,
)
from typing import Annotated
from typing import Literal


class VestingEventTrigger(VestingConditionTrigger):
    """Describes a vesting condition satisfied when a particular unscheduled event
    occurs
    """

    type: Annotated[Literal["VESTING_EVENT"], Field(description="")] = "VESTING_EVENT"
