"""Enumeration of interest accrual period types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/AccrualPeriodType.schema.json

from enum import Enum


class AccrualPeriodType(Enum):
    """Enumeration of interest accrual period types"""

    ENUM_DAILY = "DAILY"
    ENUM_MONTHLY = "MONTHLY"
    ENUM_QUARTERLY = "QUARTERLY"
    ENUM_SEMI_ANNUAL = "SEMI_ANNUAL"
    ENUM_ANNUAL = "ANNUAL"
