"""Enumeration of interest compounding types"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/CompoundingType.schema.json

from enum import Enum


class CompoundingType(Enum):
    """Enumeration of interest compounding types"""

    ENUM_COMPOUNDING = "COMPOUNDING"
    ENUM_SIMPLE = "SIMPLE"
