"""Enumeration of stock compensation types"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/CompensationType.schema.json

from enum import Enum


class CompensationType(Enum):
    """Enumeration of stock compensation types"""

    ENUM_OPTION = "OPTION"
    ENUM_RSU = "RSU"
