"""Enumeration of how the number of days are determined per period"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/DayCountType.schema.json

from enum import Enum


class DayCountType(Enum):
    """Enumeration of how the number of days are determined per period"""

    ENUM_ACTUAL_365 = "ACTUAL_365"
    ENUM_30_360 = "30_360"
