"""Enumeration of email types"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/EmailType.schema.json

from enum import Enum


class EmailType(Enum):
    """Enumeration of email types"""

    ENUM_PERSONAL = "PERSONAL"
    ENUM_BUSINESS = "BUSINESS"
    ENUM_OTHER = "OTHER"
