"""Enumeration of email types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/EmailType.schema.json

from enum import Enum


class EmailType(Enum):
    """Enumeration of email types"""

    ENUM_PERSONAL = "PERSONAL"
    ENUM_BUSINESS = "BUSINESS"
    ENUM_OTHER = "OTHER"
