"""Enumeration of recognized OCF versions"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.0.0/schema/enums/OCFVersionType.schema.json

from enum import Enum


class OCFVersionType(Enum):
    """Enumeration of recognized OCF versions"""

    ENUM_100a3 = "1.0.0-a3"
    ENUM_100b1 = "1.0.0-b1"
    ENUM_100b2 = "1.0.0-b2"
    ENUM_100b3 = "1.0.0-b3"
    ENUM_100 = "1.0.0"
