"""Enumeration of option types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/OptionType.schema.json

from enum import Enum


class OptionType(Enum):
    """Enumeration of option types"""

    ENUM_NSO = "NSO"
    ENUM_ISO = "ISO"
    ENUM_INTL = "INTL"
