"""Enumeration of time period types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/PeriodType.schema.json

from enum import Enum


class PeriodType(Enum):
    """Enumeration of time period types"""

    ENUM_DAYS = "DAYS"
    ENUM_MONTHS = "MONTHS"
    ENUM_YEARS = "YEARS"
