"""Enumeration of phone number types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/PhoneType.schema.json

from enum import Enum


class PhoneType(Enum):
    """Enumeration of phone number types"""

    ENUM_HOME = "HOME"
    ENUM_MOBILE = "MOBILE"
    ENUM_BUSINESS = "BUSINESS"
    ENUM_OTHER = "OTHER"
