"""Enumeration of rounding types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/RoundingType.schema.json

from enum import Enum


class RoundingType(Enum):
    """Enumeration of rounding types"""

    ENUM_CEILING = "CEILING"
    ENUM_FLOOR = "FLOOR"
    ENUM_NORMAL = "NORMAL"
