"""Enumeration of types of activity statuses for a stakeholder"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/StakeholderStatusType.schema.json

from enum import Enum


class StakeholderStatusType(Enum):
    """Enumeration of types of activity statuses for a stakeholder"""

    ENUM_ACTIVE = "ACTIVE"
    ENUM_LEAVE_OF_ABSENCE = "LEAVE_OF_ABSENCE"
    ENUM_TERMINATION_VOLUNTARY_OTHER = "TERMINATION_VOLUNTARY_OTHER"
    ENUM_TERMINATION_VOLUNTARY_GOOD_CAUSE = "TERMINATION_VOLUNTARY_GOOD_CAUSE"
    ENUM_TERMINATION_VOLUNTARY_RETIREMENT = "TERMINATION_VOLUNTARY_RETIREMENT"
    ENUM_TERMINATION_INVOLUNTARY_OTHER = "TERMINATION_INVOLUNTARY_OTHER"
    ENUM_TERMINATION_INVOLUNTARY_DEATH = "TERMINATION_INVOLUNTARY_DEATH"
    ENUM_TERMINATION_INVOLUNTARY_DISABILITY = "TERMINATION_INVOLUNTARY_DISABILITY"
    ENUM_TERMINATION_INVOLUNTARY_WITH_CAUSE = "TERMINATION_INVOLUNTARY_WITH_CAUSE"
