"""Enumeration of issuance types where we want to draw attention to some unique"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/StockIssuanceType.schema.json

from enum import Enum


class StockIssuanceType(Enum):
    """Enumeration of issuance types where we want to draw attention to some unique
    aspect of a stock issuance (e.g. is it an RSA)
    """

    ENUM_RSA = "RSA"
    ENUM_FOUNDERS_STOCK = "FOUNDERS_STOCK"
