"""Enumeration of stock class types"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/enums/StockClassType.schema.json

from enum import Enum


class StockClassType(Enum):
    """Enumeration of stock class types"""

    ENUM_COMMON = "COMMON"
    ENUM_PREFERRED = "PREFERRED"
