"""Enumeration of termination window types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/TerminationWindowType.schema.json

from enum import Enum


class TerminationWindowType(Enum):
    """Enumeration of termination window types"""

    ENUM_VOLUNTARY_OTHER = "VOLUNTARY_OTHER"
    ENUM_VOLUNTARY_GOOD_CAUSE = "VOLUNTARY_GOOD_CAUSE"
    ENUM_VOLUNTARY_RETIREMENT = "VOLUNTARY_RETIREMENT"
    ENUM_INVOLUNTARY_OTHER = "INVOLUNTARY_OTHER"
    ENUM_INVOLUNTARY_DEATH = "INVOLUNTARY_DEATH"
    ENUM_INVOLUNTARY_DISABILITY = "INVOLUNTARY_DISABILITY"
    ENUM_INVOLUNTARY_WITH_CAUSE = "INVOLUNTARY_WITH_CAUSE"
