"""Enumeration of valuation types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/ValuationType.schema.json

from enum import Enum


class ValuationType(Enum):
    """Enumeration of valuation types"""

    ENUM_409A = "409A"
