"""Enumeration of vesting trigger types"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/enums/VestingTriggerType.schema.json

from enum import Enum


class VestingTriggerType(Enum):
    """Enumeration of vesting trigger types"""

    ENUM_VESTING_START_DATE = "VESTING_START_DATE"
    ENUM_VESTING_SCHEDULE_ABSOLUTE = "VESTING_SCHEDULE_ABSOLUTE"
    ENUM_VESTING_SCHEDULE_RELATIVE = "VESTING_SCHEDULE_RELATIVE"
    ENUM_VESTING_EVENT = "VESTING_EVENT"
