"""Abstract file to be extended by all other files"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/primitives/files/File.schema.json

from pydantic import BaseModel
from pyocf.enums.filetype import FileType


class FileObject(BaseModel):
    """Abstract file to be extended by all other files"""

    # File type field (used to select proper schema for validation)
    file_type: FileType
