"""Abstract transaction object to be extended by all transaction objects that"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/main/schema/primitives/objects/transactions/StockClassTransaction.schema.jso
# n

from pydantic import BaseModel


class StockClassTransaction(BaseModel):
    """Abstract transaction object to be extended by all transaction objects that
    affect the stock class
    """

    # Identifier of the StockClass object, a subject of this transaction
    stock_class_id: str
