"""Abstract transaction object to be extended by all transaction objects that
affect the stock class"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.0.0/schema/primitives/objects/transactions/StockClassTransaction.schema.j
# son

from pydantic import BaseModel


class StockClassTransaction(BaseModel):
    """Abstract transaction object to be extended by all transaction objects that
    affect the stock class
    """

    # Identifier of the StockClass object, a subject of this transaction
    stock_class_id: str
