"""Type representation of the contact info for an individual stakeholder"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/types/ContactInfoWithoutName.schema.json

from pydantic import BaseModel
from pyocf.types.email import Email
from pyocf.types.phone import Phone
from typing import Optional


class ContactInfoWithoutName(BaseModel):
    """Type representation of the contact info for an individual stakeholder"""

    # Phone numbers to reach the contact at
    phone_numbers: Optional[list[Phone]]
    # Emails to reach the contact at
    emails: Optional[list[Email]]
