"""Type representation of the second part of an ISO 3166-2 country subdivision code"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/types/CountrySubdivisionCode.schema.json

from pydantic import constr
from pyocf.simplebase import SimpleBaseModel


class CountrySubdivisionCode(SimpleBaseModel):
    """Type representation of the second part of an ISO 3166-2 country subdivision code"""

    root: constr(pattern=r"^[A-Z0-9]{1,3}$")
