"""Type representation of an ISO 3166-1 alpha 2 country code"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/types/CountryCode.schema.json

from pydantic import constr
from pyocf.simplebase import SimpleBaseModel


class CountryCode(SimpleBaseModel):
    """Type representation of an ISO 3166-1 alpha 2 country code"""

    root: constr(pattern=r"^[A-Z]{2}$")
