"""Type representation of a file"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/main/schema/types/File.schema.json

from pydantic import BaseModel
from pyocf.types.md5 import Md5


class File(BaseModel):
    """Type representation of a file"""

    # Path to the file within the OCF container
    filepath: str
    # MD5 file checksum
    md5: Md5
