"""String representation of MD5 hash with basic validation for a string of 32
characters composed of letters (uppercase or lowercase) and numbers"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/types/Md5.schema.json

from pydantic import constr
from pyocf.simplebase import SimpleBaseModel


class Md5(SimpleBaseModel):
    """String representation of MD5 hash with basic validation for a string of 32
    characters composed of letters (uppercase or lowercase) and numbers
    """

    root: constr(pattern=r"^[a-fA-F0-9]{32}$")
