"""Type comprising of multiple name components"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.0.0/schema/types/Name.schema.json

from pydantic import BaseModel
from typing import Optional


class Name(BaseModel):
    """Type comprising of multiple name components"""

    # Legal full name for the individual/institution
    legal_name: str
    # First/given name for the individual
    first_name: Optional[str]
    # Last/family name for the individual
    last_name: Optional[str]
