"""${schema.description}"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
% for line in schema.comment.splitlines():
# ${line}
% endfor

from enum import Enum


class ${schema.name}(Enum):
    """${schema.description}
    """

    % for name, value in schema.enum:
    ${name} = "${value}"
    % endfor
