"""${schema.description.splitlines()[0]}"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
% for line in schema.comment.splitlines():
# ${line}
% endfor

from enum import Enum


class ${schema.name}(Enum):
    """${schema.description}
    """

    % for name, value in schema.enum:
    ${name} = "${value}"
    % endfor
