"""A Plan Security Issuance is a transaction to issue plan securities (it\'s a
compatibility wrapper for Equity Compensation Issuances)"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.2.0/schema/objects/transactions/issuance/PlanSecurityIssuance.schema.json

from pydantic import Field
from pyocf.objects.transactions.issuance.equitycompensationissuance import (
    EquityCompensationIssuance,
)
from typing import Annotated
from typing import Literal


class PlanSecurityIssuance(EquityCompensationIssuance):
    """A Plan Security Issuance is a transaction to issue plan securities (it\'s a
    compatibility wrapper for Equity Compensation Issuances)
    """

    object_type: Annotated[
        Literal["TX_PLAN_SECURITY_ISSUANCE"], Field(description="")
    ] = "TX_PLAN_SECURITY_ISSUANCE"
