"""Abstract object describing a security retraction transaction"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.2.0/schema/primitives/objects/transactions/retraction/Retraction.schema.j
# son

from pydantic import BaseModel
from pydantic import Field
from typing import Annotated


class Retraction(BaseModel):
    """Abstract object describing a security retraction transaction"""

    reason_text: Annotated[str, Field(description="Reason for the retraction")]
