"""Object describing plan security retraction transaction (a compatibility wrapper
for equity compensation retraction event)"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.2.0/schema/objects/transactions/retraction/PlanSecurityRetraction.schema.
# json

from pydantic import Field
from pyocf.objects.transactions.retraction.equitycompensationretraction import (
    EquityCompensationRetraction,
)
from typing import Annotated
from typing import Literal


class PlanSecurityRetraction(EquityCompensationRetraction):
    """Object describing plan security retraction transaction (a compatibility wrapper
    for equity compensation retraction event)
    """

    object_type: Annotated[
        Literal["TX_PLAN_SECURITY_RETRACTION"], Field(description="")
    ] = "TX_PLAN_SECURITY_RETRACTION"
