"""Top-level schema describing the OCF Manifest, which holds issuer information and
references ocf files containing transactions, stakeholders, stock classes, etc."""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2024 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.2.0/schema/files/OCFManifestFile.schema.json

from pydantic import Field
from pyocf.objects.issuer import Issuer
from pyocf.primitives.files.file import FileObject
from pyocf.types.date import Date
from pyocf.types.file import File
from typing import Annotated
from typing import Literal
from typing import Optional


class OCFManifestFile(FileObject):
    """Top-level schema describing the OCF Manifest, which holds issuer information and
    references ocf files containing transactions, stakeholders, stock classes, etc.
    """

    ocf_version: Annotated[
        Literal["1.2.0"],
        Field(
            description="OCF Version Identifier -- the current semantic version"
            "(https://semver.org/spec/v2.0.0.html)"
        ),
    ] = "1.2.0"
    file_type: Annotated[Literal["OCF_MANIFEST_FILE"], Field(description="")] = (
        "OCF_MANIFEST_FILE"
    )
    issuer: Annotated[Issuer, Field(description="Issuer for the cap table")]
    as_of: Annotated[
        Date, Field(description="The point-in-time represented by this OCF Package")
    ]
    generated_at: Annotated[
        str,
        Field(
            description="Timestamp of when the package was generated. Useful when determining which set"
            "of data is most up-to-date, if presented with two packages that have the same"
            "`as_of` date, but different cap table data."
        ),
    ]
    comments: Optional[
        Annotated[
            list[str],
            Field(
                description="Unstructured text comments related to and stored for the cap table"
            ),
        ]
    ] = None
    stock_plans_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer stock plans, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/stock_plans_file schema to validate loaded files)"
        ),
    ]
    stock_legend_templates_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer stock legend templates, indexed from"
            "the file containing the first such object created to the file containing the"
            "last (See separate /schema/files/stock_legend_templates_file schema to validate"
            "loaded files)"
        ),
    ]
    stock_classes_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer stock classes, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/stock_classes_file schema to validate loaded files)"
        ),
    ]
    vesting_terms_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer vesting terms, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/vesting_terms_file schema to validate loaded files)"
        ),
    ]
    valuations_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer valuations, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/valuations_file schema to validate loaded files)"
        ),
    ]
    transactions_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer transactions, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/transactions_file schema to validate loaded files)"
        ),
    ]
    stakeholders_files: Annotated[
        list[File],
        Field(
            description="List of files containing lists of issuer stakeholders, indexed from the file"
            "containing the first such object created to the file containing the last (See"
            "separate /schema/files/stakeholders_file schema to validate loaded files)"
        ),
    ]
    financings_files: Optional[
        Annotated[
            list[File],
            Field(
                description="List of files containing lists of financings, indexed from the file containing"
                "the first such object created to the file containing the last (See separate"
                "/schema/files/financings_file schema to validate loaded files)"
            ),
        ]
    ] = None
    documents_files: Optional[
        Annotated[
            list[File],
            Field(
                description="List of files containing lists of document paths, indexed from the file"
                "containing the first such object created to the file containing the last (See"
                "separate /schema/files/documents_file schema to validate loaded files)"
            ),
        ]
    ] = None
