"""JSON containing file type identifier and list of stakeholders"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.0.0/schema/files/StakeholdersFile.schema.json

from pyocf.objects.stakeholder import Stakeholder
from pyocf.primitives.files.file import FileObject
from typing import Literal


class StakeholdersFile(FileObject):
    """JSON containing file type identifier and list of stakeholders"""

    # List of OCF stakeholder objects
    items: list[Stakeholder]
    file_type: Literal["OCF_STAKEHOLDERS_FILE"] = "OCF_STAKEHOLDERS_FILE"
