"""JSON containing file type identifier and list of vesting terms"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-
# OCF/tree/v1.0.0/schema/files/VestingTermsFile.schema.json

from pyocf.objects.vestingterms import VestingTerms
from pyocf.primitives.files.file import FileObject
from typing import Literal


class VestingTermsFile(FileObject):
    """JSON containing file type identifier and list of vesting terms"""

    # List of OCF vesting terms objects
    items: list[VestingTerms]
    file_type: Literal["OCF_VESTING_TERMS_FILE"] = "OCF_VESTING_TERMS_FILE"
