"""Describes how a security converts into a fixed amount of a stock class"""

# Autogenerated, do not edit.
# Copyright © 2023 Shoobx, Fidelity Investments
#
# Based on the Open Captable Format schema:
# Copyright © 2023 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/main/schema/types/conversion_mechanisms/FixedAmountConversionMechanism.schem
# a.json

from pyocf.primitives.types.conversion_mechanisms.conversionmechanism import (
    ConversionMechanism,
)
from pyocf.types.numeric import Numeric
from typing import Literal


class FixedAmountConversionMechanism(ConversionMechanism):
    """Describes how a security converts into a fixed amount of a stock class"""

    type: Literal["FIXED_AMOUNT_CONVERSION"] = "FIXED_AMOUNT_CONVERSION"
    # How many shares of target Stock Class does this security convert into?
    converts_to_quantity: Numeric
