"""Sets forth inputs and conversion mechanism of percent of capitalization
conversion (where an instrument purports to grant a percent of company
capitalization at some point in time)"""

# Autogenerated, do not edit.
# Copyright © 2023 FMR LLC
#
# Based on the Open Captable Format schema:
# Copyright © 2022 Open Cap Table Coalition (https://opencaptablecoalition.com) /
# Original File: https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/t
# ree/v1.0.0/schema/types/conversion_mechanisms/PercentCapitalizationConversionMec
# hanism.schema.json

from pyocf.primitives.types.conversion_mechanisms.conversionmechanism import (
    ConversionMechanism,
)
from pyocf.types.percentage import Percentage
from typing import Literal
from typing import Optional


class PercentCapitalizationConversionMechanism(ConversionMechanism):
    """Sets forth inputs and conversion mechanism of percent of capitalization
    conversion (where an instrument purports to grant a percent of company
    capitalization at some point in time)
    """

    type: Literal[
        "FIXED_PERCENT_OF_CAPITALIZATION_CONVERSION"
    ] = "FIXED_PERCENT_OF_CAPITALIZATION_CONVERSION"
    # What percentage of the company capitalization does this convert to
    converts_to_percent: Percentage
    # How is company capitalization defined for purposes of conversion? If possible,
    # include the legal language from the instrument.
    capitalization_definition: Optional[str]
